import type { SkillLineDef } from "./types";

export const skillLines: SkillLineDef[] = [
  {
    id: "dk-flame",
    name: "Пылающий огонь",
    classId: "dragonknight",
    skills: [
      {
        id: "lava-whip",
        name: "Удар лавы / Плеть",
        lineId: "dk-flame",
        kind: "active",
        maxStatCoeff: 0.1136,
        maxDamageCoeff: 1.193,
        cost: "magicka",
        description: "Спел-спам. Высокий коэффициент, оглушение при статусе.",
        maxRank: 4,
        levelingNote: "Качайте первым: основной спам-скилл линии.",
      },
      {
        id: "eruption",
        name: "Извержение",
        lineId: "dk-flame",
        kind: "active",
        maxStatCoeff: 0.077,
        maxDamageCoeff: 0.81,
        ticks: 10,
        duration: 10,
        isDot: true,
        cost: "magicka",
        description: "AoE DoT под ногами.",
        maxRank: 4,
        levelingNote: "Второе: постоянный урон в мили.",
      },
      {
        id: "flames-of-oblivion",
        name: "Пламя Обливиона",
        lineId: "dk-flame",
        kind: "passive",
        maxStatCoeff: 0,
        maxDamageCoeff: 0,
        description: "Автоатаки огнём, бонус к силе заклинаний/оружия.",
        mods: { spellDamagePct: 0.05, weaponDamagePct: 0.05 },
        maxRank: 2,
        rankMods: { spellDamagePct: 0.03, weaponDamagePct: 0.03 },
        levelingNote: "Пассивка на урон — берите сразу после спама.",
      },
    ],
  },
  {
    id: "dk-earth",
    name: "Каменное сердце",
    classId: "dragonknight",
    skills: [
      {
        id: "obsidian-shield",
        name: "Обсидиановый щит",
        lineId: "dk-earth",
        kind: "active",
        maxStatCoeff: 0.16,
        maxDamageCoeff: 0.2,
        cost: "magicka",
        description: "Щит группе. Больше ХП = больше щит.",
        maxRank: 4,
        levelingNote: "Для танка/группы. В соло DPS можно не качать рано.",
      },
      {
        id: "igneous-shield",
        name: "Огненный щит (хил/танк)",
        lineId: "dk-earth",
        kind: "passive",
        maxStatCoeff: 0,
        maxDamageCoeff: 0,
        description: "Бонус к броне и здоровью от тяжёлой брони / щитов.",
        mods: { healthPct: 0.05, physicalResist: 1320, spellResist: 1320 },
        maxRank: 2,
        levelingNote: "Обязательна танку.",
      },
    ],
  },
  {
    id: "dk-draconic",
    name: "Драконья сила",
    classId: "dragonknight",
    skills: [
      {
        id: "coagulating-blood",
        name: "Сгущающаяся кровь",
        lineId: "dk-draconic",
        kind: "active",
        maxStatCoeff: 0.12,
        maxDamageCoeff: 1.05,
        isHeal: true,
        cost: "magicka",
        description: "Сильный селф-хил, растёт от недостающего ХП.",
        maxRank: 4,
        levelingNote: "Соло и танк: качайте для выживаемости.",
      },
      {
        id: "helping-hands",
        name: "Руки помощи",
        lineId: "dk-draconic",
        kind: "passive",
        maxStatCoeff: 0,
        maxDamageCoeff: 0,
        description: "Реген стамины при использовании драконьих скиллов.",
        mods: { staminaRecovery: 180 },
        maxRank: 2,
        levelingNote: "Сустейн танка/стамины.",
      },
    ],
  },
  {
    id: "sorc-daedric",
    name: "Даэдрическое призывание",
    classId: "sorcerer",
    skills: [
      {
        id: "crystal-frags",
        name: "Кристальные осколки",
        lineId: "sorc-daedric",
        kind: "active",
        maxStatCoeff: 0.118,
        maxDamageCoeff: 1.24,
        cost: "magicka",
        description: "Burst-прок. Один из самых высоких коэффициентов.",
        maxRank: 4,
        levelingNote: "Главный спелл чародея — качайте сразу.",
      },
      {
        id: "bound-aegis",
        name: "Связанная эгида",
        lineId: "sorc-daedric",
        kind: "passive",
        maxStatCoeff: 0,
        maxDamageCoeff: 0,
        description: "Макс. магия и сопротивление заклинаниям.",
        mods: { magickaPct: 0.08, spellResist: 1000 },
        maxRank: 2,
        rankMods: { magickaPct: 0.02 },
        levelingNote: "Пассивка на пул магии — ранняя прокачка.",
      },
    ],
  },
  {
    id: "sorc-storm",
    name: "Ударная буря",
    classId: "sorcerer",
    skills: [
      {
        id: "mystic-orb",
        name: "Мистическая сфера / Endless Hail analog",
        lineId: "sorc-storm",
        kind: "active",
        maxStatCoeff: 0.09,
        maxDamageCoeff: 0.95,
        isDot: true,
        ticks: 6,
        duration: 8,
        cost: "magicka",
        description: "Молнии и AoE. Для парса держите на баре.",
        maxRank: 4,
        levelingNote: "AoE и статус Shock.",
      },
      {
        id: "power-surge",
        name: "Прилив силы",
        lineId: "sorc-storm",
        kind: "active",
        maxStatCoeff: 0.05,
        maxDamageCoeff: 0.4,
        isHeal: true,
        cost: "magicka",
        description: "Major Sorcery + хил с критов.",
        mods: { spellDamagePct: 0.2 },
        maxRank: 4,
        levelingNote: "Бафф силы заклинаний — обязателен.",
      },
    ],
  },
  {
    id: "sorc-dark",
    name: "Тёмная магия",
    classId: "sorcerer",
    skills: [
      {
        id: "hardened-ward",
        name: "Укреплённый щит",
        lineId: "sorc-dark",
        kind: "active",
        maxStatCoeff: 0.2,
        maxDamageCoeff: 0.1,
        cost: "magicka",
        description: "Большой щит от магии.",
        maxRank: 4,
        levelingNote: "Соло/PvP. В рейде DPS можно позже.",
      },
    ],
  },
  {
    id: "nb-assassin",
    name: "Убийство",
    classId: "nightblade",
    skills: [
      {
        id: "surprise-attack",
        name: "Внезапная атака",
        lineId: "nb-assassin",
        kind: "active",
        maxStatCoeff: 0.11363,
        maxDamageCoeff: 1.1931,
        cost: "stamina",
        description: "Основной спам стамины. Пробитие брони.",
        maxRank: 4,
        levelingNote: "Качайте первым на стам-NB.",
      },
      {
        id: "grim-focus",
        name: "Мрачная сосредоточенность",
        lineId: "nb-assassin",
        kind: "active",
        maxStatCoeff: 0.1,
        maxDamageCoeff: 1.1,
        cost: "magicka",
        description: "Стак на лёгкие атаки, затем луч.",
        maxRank: 4,
        levelingNote: "Парс NB: после спама.",
      },
      {
        id: "hemorrhage",
        name: "Кровотечение",
        lineId: "nb-assassin",
        kind: "passive",
        maxStatCoeff: 0,
        maxDamageCoeff: 0,
        description: "Крит-урон.",
        mods: { critDamage: 0.1 },
        maxRank: 2,
        levelingNote: "Ключевая пассивка крита.",
      },
    ],
  },
  {
    id: "nb-shadow",
    name: "Тень",
    classId: "nightblade",
    skills: [
      {
        id: "refreshing-path",
        name: "Обновляющий путь",
        lineId: "nb-shadow",
        kind: "active",
        maxStatCoeff: 0.04,
        maxDamageCoeff: 0.3,
        isHeal: true,
        cost: "magicka",
        description: "Хил и Major Expedition по пути.",
        mods: { healthRecovery: 200, magickaRecovery: 150, staminaRecovery: 150 },
        maxRank: 4,
        levelingNote: "Мобильность и сустейн.",
      },
    ],
  },
  {
    id: "nb-siphon",
    name: "Вытягивание",
    classId: "nightblade",
    skills: [
      {
        id: "siphoning-attacks",
        name: "Вытягивающие атаки",
        lineId: "nb-siphon",
        kind: "active",
        maxStatCoeff: 0.03,
        maxDamageCoeff: 0.2,
        isHeal: true,
        cost: "magicka",
        description: "Реген ресурсов с лёгких атак.",
        mods: { magickaRecovery: 250, staminaRecovery: 250 },
        maxRank: 4,
        levelingNote: "Сустейн. Качайте, если не хватает регена.",
      },
      {
        id: "catalyst",
        name: "Катализатор",
        lineId: "nb-siphon",
        kind: "passive",
        maxStatCoeff: 0,
        maxDamageCoeff: 0,
        description: "Ульт от зелий.",
        mods: { magickaRecoveryPct: 0.05, staminaRecoveryPct: 0.05 },
        maxRank: 2,
        levelingNote: "Пассивка сустейна.",
      },
    ],
  },
  {
    id: "templar-aedric",
    name: "Копьё Эдры",
    classId: "templar",
    skills: [
      {
        id: "puncturing-sweep",
        name: "Пронзающий замах",
        lineId: "templar-aedric",
        kind: "active",
        maxStatCoeff: 0.1,
        maxDamageCoeff: 1.05,
        cost: "magicka",
        isHeal: true,
        description: "Спам-конус + вампиризм.",
        maxRank: 4,
        levelingNote: "Главный скилл храмовника.",
      },
    ],
  },
  {
    id: "templar-dawn",
    name: "Гнев рассвета",
    classId: "templar",
    skills: [
      {
        id: "vampire-sacrifice",
        name: "Жертва / Radiant Oppression analog",
        lineId: "templar-dawn",
        kind: "ultimate",
        maxStatCoeff: 0.13,
        maxDamageCoeff: 1.35,
        cost: "magicka",
        description: "Луч ульты. Очень высокий урон в одну цель.",
        maxRank: 4,
        levelingNote: "Качайте ульту параллельно копью.",
      },
      {
        id: "illuminate",
        name: "Озарение",
        lineId: "templar-dawn",
        kind: "passive",
        maxStatCoeff: 0,
        maxDamageCoeff: 0,
        description: "Сила заклинаний от скиллов рассвета.",
        mods: { spellDamage: 129 },
        maxRank: 2,
        levelingNote: "Пассивка урона.",
      },
    ],
  },
  {
    id: "templar-restoring",
    name: "Восстанавливающий свет",
    classId: "templar",
    skills: [
      {
        id: "breath-of-life",
        name: "Дыхание жизни",
        lineId: "templar-restoring",
        kind: "active",
        maxStatCoeff: 0.11,
        maxDamageCoeff: 1.15,
        isHeal: true,
        cost: "magicka",
        description: "Бурст-хил по 3 целям.",
        maxRank: 4,
        levelingNote: "Хилеру — первый скилл. DPS может отложить.",
      },
      {
        id: "sacred-ground",
        name: "Святая земля",
        lineId: "templar-restoring",
        kind: "passive",
        maxStatCoeff: 0,
        maxDamageCoeff: 0,
        description: "Хил и Minor Mending в рунах.",
        mods: { healingDonePct: 0.08, healthRecovery: 180 },
        maxRank: 2,
        levelingNote: "Хил и реген ХП в зоне.",
      },
    ],
  },
  {
    id: "warden-animal",
    name: "Спутники животных",
    classId: "warden",
    skills: [
      {
        id: "cutting-dive",
        name: "Рассекающее пике",
        lineId: "warden-animal",
        kind: "active",
        maxStatCoeff: 0.11,
        maxDamageCoeff: 1.16,
        cost: "stamina",
        description: "Спам-птица. Мобильность.",
        maxRank: 4,
        levelingNote: "Стам-хранитель: качайте первым.",
      },
      {
        id: "advanced-species",
        name: "Развитые виды",
        lineId: "warden-animal",
        kind: "passive",
        maxStatCoeff: 0,
        maxDamageCoeff: 0,
        description: "Сила оружия/заклинаний от животных скиллов.",
        mods: { weaponDamagePct: 0.06, spellDamagePct: 0.06 },
        maxRank: 2,
        levelingNote: "Пассивка урона.",
      },
    ],
  },
  {
    id: "warden-green",
    name: "Зелёный баланс",
    classId: "warden",
    skills: [
      {
        id: "soothing-spores",
        name: "Успокаивающие споры",
        lineId: "warden-green",
        kind: "active",
        maxStatCoeff: 0.1,
        maxDamageCoeff: 1.05,
        isHeal: true,
        cost: "magicka",
        description: "Хил по группе + HoT.",
        maxRank: 4,
        levelingNote: "Хилер-хранитель: приоритет.",
      },
      {
        id: "maturation",
        name: "Созревание",
        lineId: "warden-green",
        kind: "passive",
        maxStatCoeff: 0,
        maxDamageCoeff: 0,
        description: "Хил и здоровье.",
        mods: { healingDonePct: 0.06, health: 1000 },
        maxRank: 2,
        levelingNote: "Пассивка хила.",
      },
    ],
  },
  {
    id: "warden-winter",
    name: "Зимняя ярость",
    classId: "warden",
    skills: [
      {
        id: "fetcher-infection",
        name: "Заражение / Arctic blast analog",
        lineId: "warden-winter",
        kind: "active",
        maxStatCoeff: 0.08,
        maxDamageCoeff: 0.85,
        isDot: true,
        ticks: 8,
        duration: 10,
        cost: "magicka",
        description: "DoT и контроль.",
        maxRank: 4,
        levelingNote: "Для парса и танка — статус Chilled.",
      },
    ],
  },
  {
    id: "necro-grave",
    name: "Могильный владыка",
    classId: "necromancer",
    skills: [
      {
        id: "blastbones",
        name: "Взрывные кости",
        lineId: "necro-grave",
        kind: "active",
        maxStatCoeff: 0.115,
        maxDamageCoeff: 1.21,
        cost: "magicka",
        description: "Скелет-снаряд. Ядро парса некроманта.",
        maxRank: 4,
        levelingNote: "Качайте первым.",
      },
    ],
  },
  {
    id: "necro-bone",
    name: "Костяной тиран",
    classId: "necromancer",
    skills: [
      {
        id: "bone-armor",
        name: "Костяная броня",
        lineId: "necro-bone",
        kind: "active",
        maxStatCoeff: 0.02,
        maxDamageCoeff: 0.1,
        cost: "magicka",
        description: "Major Resolve, сопротивления.",
        mods: { physicalResist: 5948, spellResist: 5948 },
        maxRank: 4,
        levelingNote: "Танк/соло.",
      },
    ],
  },
  {
    id: "necro-living",
    name: "Живая смерть",
    classId: "necromancer",
    skills: [
      {
        id: "render-flesh",
        name: "Плоть",
        lineId: "necro-living",
        kind: "active",
        maxStatCoeff: 0.108,
        maxDamageCoeff: 1.13,
        isHeal: true,
        cost: "magicka",
        description: "Бурст-хил.",
        maxRank: 4,
        levelingNote: "Хилер-некро: приоритет.",
      },
    ],
  },
  {
    id: "arc-herald",
    name: "Глашатай томов",
    classId: "arcanist",
    skills: [
      {
        id: "fatecarver",
        name: "Резчик судеб",
        lineId: "arc-herald",
        kind: "active",
        maxStatCoeff: 0.12,
        maxDamageCoeff: 1.26,
        ticks: 7,
        duration: 4.5,
        cost: "magicka",
        description: "Луч. Основной урон арканиста.",
        maxRank: 4,
        levelingNote: "Качайте первым всегда.",
      },
      {
        id: "writhing-runeblades",
        name: "Извивающиеся клинки рун",
        lineId: "arc-herald",
        kind: "active",
        maxStatCoeff: 0.1,
        maxDamageCoeff: 1.05,
        cost: "magicka",
        description: "Спам до луча, стаки Crux.",
        maxRank: 4,
        levelingNote: "Сразу после Fatecarver.",
      },
    ],
  },
  {
    id: "arc-soldier",
    name: "Солдат апокрифа",
    classId: "arcanist",
    skills: [
      {
        id: "runeguard",
        name: "Страж рун",
        lineId: "arc-soldier",
        kind: "active",
        maxStatCoeff: 0.03,
        maxDamageCoeff: 0.2,
        cost: "magicka",
        description: "Щит и Minor Resolve.",
        mods: { physicalResist: 2974, spellResist: 2974 },
        maxRank: 4,
        levelingNote: "Защита. Танку раньше, DPS позже.",
      },
    ],
  },
  {
    id: "arc-curative",
    name: "Целительные руны",
    classId: "arcanist",
    skills: [
      {
        id: "reconstructive-domain",
        name: "Область восстановления",
        lineId: "arc-curative",
        kind: "active",
        maxStatCoeff: 0.09,
        maxDamageCoeff: 0.9,
        isHeal: true,
        cost: "magicka",
        description: "Зона хила.",
        maxRank: 4,
        levelingNote: "Хилер-арканист.",
      },
    ],
  },
  {
    id: "dest-staff",
    name: "Посох разрушения",
    skills: [
      {
        id: "crushing-shock",
        name: "Сокрушающий удар",
        lineId: "dest-staff",
        kind: "active",
        maxStatCoeff: 0.1,
        maxDamageCoeff: 1.05,
        cost: "magicka",
        description: "Спам посоха. Прерывание.",
        maxRank: 4,
        levelingNote: "Линия посоха разрушения: качайте вместе с классом.",
      },
      {
        id: "wall-of-elements",
        name: "Стена стихий / Unstable Wall",
        lineId: "dest-staff",
        kind: "active",
        maxStatCoeff: 0.08,
        maxDamageCoeff: 0.84,
        isDot: true,
        ticks: 8,
        duration: 10,
        cost: "magicka",
        description: "AoE на бэкбаре.",
        maxRank: 4,
        levelingNote: "Ставьте на бэкбар с посохом молний.",
      },
    ],
  },
  {
    id: "resto-staff",
    name: "Посох восстановления",
    skills: [
      {
        id: "healing-springs",
        name: "Целебные родники",
        lineId: "resto-staff",
        kind: "active",
        maxStatCoeff: 0.1,
        maxDamageCoeff: 1.02,
        isHeal: true,
        cost: "magicka",
        description: "Основной хил посоха.",
        maxRank: 4,
        levelingNote: "Хилеру — сразу.",
      },
      {
        id: "combat-prayer",
        name: "Боевая молитва",
        lineId: "resto-staff",
        kind: "active",
        maxStatCoeff: 0.06,
        maxDamageCoeff: 0.6,
        isHeal: true,
        cost: "magicka",
        description: "Minor Berserk группе.",
        maxRank: 4,
        levelingNote: "Бафф урона рейда.",
      },
    ],
  },
  {
    id: "bow",
    name: "Лук",
    skills: [
      {
        id: "endless-hail",
        name: "Бесконечный град",
        lineId: "bow",
        kind: "active",
        maxStatCoeff: 0.08,
        maxDamageCoeff: 0.84,
        isDot: true,
        ticks: 8,
        duration: 10,
        cost: "stamina",
        description: "AoE бэкбара.",
        maxRank: 4,
        levelingNote: "Стам-DPS: бэкбар.",
      },
      {
        id: "poison-injection",
        name: "Впрыск яда",
        lineId: "bow",
        kind: "active",
        maxStatCoeff: 0.1,
        maxDamageCoeff: 1.08,
        isDot: true,
        ticks: 6,
        duration: 10,
        cost: "stamina",
        description: "DoT, сильнее по раненым.",
        maxRank: 4,
        levelingNote: "Держите в ротации.",
      },
    ],
  },
  {
    id: "twohanded",
    name: "Двуручное оружие",
    skills: [
      {
        id: "stampede",
        name: "Натиск",
        lineId: "twohanded",
        kind: "active",
        maxStatCoeff: 0.11,
        maxDamageCoeff: 1.15,
        cost: "stamina",
        description: "Спам 2H.",
        maxRank: 4,
        levelingNote: "Если фронт — двуручное.",
      },
    ],
  },
  {
    id: "dual-wield",
    name: "Парное оружие",
    skills: [
      {
        id: "rapid-strikes",
        name: "Стремительные удары",
        lineId: "dual-wield",
        kind: "active",
        maxStatCoeff: 0.113,
        maxDamageCoeff: 1.19,
        cost: "stamina",
        description: "Спам парников.",
        maxRank: 4,
        levelingNote: "Стам мили: первый скилл оружия.",
      },
    ],
  },
  {
    id: "onehand-shield",
    name: "Одноручное и щит",
    skills: [
      {
        id: "puncturing-remedy",
        name: "Пронзающее возмездие",
        lineId: "onehand-shield",
        kind: "active",
        maxStatCoeff: 0.08,
        maxDamageCoeff: 0.7,
        cost: "stamina",
        description: "Таунт и хил танка.",
        isHeal: true,
        maxRank: 4,
        levelingNote: "Танку качайте первым в линии щита.",
      },
    ],
  },
];
